/*
  Network Simulation Cradle
  Copyright (C) 2003-2005 Sam Jansen

  This program is free software; you can redistribute it and/or modify it
  under the terms of the GNU General Public License as published by the Free
  Software Foundation; either version 2 of the License, or (at your option)
  any later version.

  This program is distributed in the hope that it will be useful, but WITHOUT
  ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
  FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
  more details.

  You should have received a copy of the GNU General Public License along
  with this program; if not, write to the Free Software Foundation, Inc., 59
  Temple Place, Suite 330, Boston, MA 02111-1307 USA
 */
#define UNIMPLEMENTED() nsc_assert(0, __func__);
#define U(func) void func(void) { UNIMPLEMENTED() }
extern void nsc_assert(int, const char *);

U(__alloc_pages)
U(__copy_from_user_ll)
U(__down_read)
U(__down_read_trylock)
U(__down_write)
U(__down_write_trylock)
U(__downgrade_write)
U(__free_pages)
U(__kill_fasync)
U(__mark_inode_dirty)
U(__up_read)
U(__up_write)
U(__vmalloc)
U(__xfrm_state_destroy)
U(account_system_time)
U(account_system_time_scaled)
U(account_user_time)
U(account_user_time_scaled)
U(add_wait_queue)
U(add_wait_queue_exclusive)
U(autoremove_wake_function)
U(clock_t_to_jiffies)
U(cmpxchg_386_u16)
U(cmpxchg_386_u32)
U(cmpxchg_386_u8)
U(complete)
U(crypto_aead_setauthsize)
U(crypto_alloc_aead)
U(crypto_alloc_base)
U(current_fs_time)
U(d_alloc)
U(d_instantiate)
U(default_wake_function)
U(device_del)
U(device_rename)
U(dirty_ratio_handler)
U(dirty_writeback_centisecs_handler)
U(drop_caches_sysctl_handler)
U(dynamic_dname)
U(f_getown)
U(f_setown)
U(fasync_helper)
U(fd_install)
U(fget)
U(fget_light)
U(find_task_by_vpid)
U(fput)
U(generic_pipe_buf_confirm)
U(generic_pipe_buf_map)
U(generic_pipe_buf_unmap)
U(generic_splice_sendpage)
U(get_empty_filp)
U(get_options)
U(get_sb_pseudo)
U(get_unused_fd)
U(get_unused_fd_flags)
U(getnstimeofday)
U(hrtimer_cancel)
U(hrtimer_get_remaining)
U(hrtimer_init)
U(hrtimer_start)
U(hrtimer_try_to_cancel)
U(in_egroup_p)
U(init_file)
U(ip6_mroute_getsockopt)
U(ip6_mroute_setsockopt)
U(ipv6_ext_hdr)
U(ipv6_skip_exthdr)
U(jiffies_to_clock_t)
U(jiffies_to_msecs)
U(jiffies_to_timeval)
U(kill_anon_super)
U(kill_pid_info)
U(km_new_mapping)
U(kmem_cache_destroy)
U(kobject_get)
U(kobject_put)
U(kthread_bind)
U(kthread_create)
U(kthread_should_stop)
U(lowmem_reserve_ratio_sysctl_handler)
U(min_free_kbytes_sysctl_handler)
U(monotonic_to_bootbased)
U(mutex_trylock)
U(native_read_tsc)
U(no_llseek)
U(param_get_int)
U(param_set_int)
U(percpu_pagelist_fraction_sysctl_handler)
U(proc_nr_files)
U(pskb_put)
U(put_device)
U(put_filp)
U(put_unused_fd)
U(remove_wait_queue)
U(run_posix_cpu_timers)
U(sched_rt_handler)
U(send_sigurg)
U(seq_printf)
U(set_process_cpu_timer)
U(sg_init_one)
U(sg_init_table)
U(simple_lookup)
U(simple_statfs)
U(simple_strtoul)
U(skb_icv_walk)
U(splice_to_pipe)
U(strncpy_from_user)
U(sys_close)
U(timeval_to_jiffies)
U(touch_atime)
U(vfree)
U(wait_for_completion)
U(wait_on_sync_kiocb)
U(wake_up_process)
U(xfrm4_rcv)
U(xfrm_aalg_get_byname)
U(xfrm_input_resume)
U(xfrm_output_resume)
U(xfrm_state_lookup)
U(xfrm_unregister_type)
U(yield)
