# 1 "globaliser/test/static_local_self_ref.c"
# 1 "<built-in>"
# 1 "<command-line>"
# 1 "globaliser/test/static_local_self_ref.c"
#include "num_stacks.h"
void func()
{
    typedef  int  _GLOBAL_0_T; static  _GLOBAL_0_T  global_sl_self_ref[NUM_STACKS] = {  sizeof ( global_sl_self_ref[0] )  ,  sizeof ( global_sl_self_ref[1] )  ,  sizeof ( global_sl_self_ref[2] )  ,  sizeof ( global_sl_self_ref[3] )  ,  sizeof ( global_sl_self_ref[4] )  ,  sizeof ( global_sl_self_ref[5] )  ,  sizeof ( global_sl_self_ref[6] )  ,  sizeof ( global_sl_self_ref[7] )  ,  sizeof ( global_sl_self_ref[8] )  ,  sizeof ( global_sl_self_ref[9] )  ,  sizeof ( global_sl_self_ref[10] )  ,  sizeof ( global_sl_self_ref[11] )  ,  sizeof ( global_sl_self_ref[12] )  ,  sizeof ( global_sl_self_ref[13] )  ,  sizeof ( global_sl_self_ref[14] )  ,  sizeof ( global_sl_self_ref[15] )  ,  sizeof ( global_sl_self_ref[16] )  ,  sizeof ( global_sl_self_ref[17] )  ,  sizeof ( global_sl_self_ref[18] )  ,  sizeof ( global_sl_self_ref[19] )  ,  sizeof ( global_sl_self_ref[20] )  ,  sizeof ( global_sl_self_ref[21] )  ,  sizeof ( global_sl_self_ref[22] )  ,  sizeof ( global_sl_self_ref[23] )  ,  sizeof ( global_sl_self_ref[24] )  ,  sizeof ( global_sl_self_ref[25] )  ,  sizeof ( global_sl_self_ref[26] )  ,  sizeof ( global_sl_self_ref[27] )  ,  sizeof ( global_sl_self_ref[28] )  ,  sizeof ( global_sl_self_ref[29] )  ,  sizeof ( global_sl_self_ref[30] )  ,  sizeof ( global_sl_self_ref[31] )  ,  sizeof ( global_sl_self_ref[32] )  ,  sizeof ( global_sl_self_ref[33] )  ,  sizeof ( global_sl_self_ref[34] )  ,  sizeof ( global_sl_self_ref[35] )  ,  sizeof ( global_sl_self_ref[36] )  ,  sizeof ( global_sl_self_ref[37] )  ,  sizeof ( global_sl_self_ref[38] )  ,  sizeof ( global_sl_self_ref[39] )  ,  sizeof ( global_sl_self_ref[40] )  ,  sizeof ( global_sl_self_ref[41] )  ,  sizeof ( global_sl_self_ref[42] )  ,  sizeof ( global_sl_self_ref[43] )  ,  sizeof ( global_sl_self_ref[44] )  ,  sizeof ( global_sl_self_ref[45] )  ,  sizeof ( global_sl_self_ref[46] )  ,  sizeof ( global_sl_self_ref[47] )  ,  sizeof ( global_sl_self_ref[48] )  ,  sizeof ( global_sl_self_ref[49] )  ,  };     
}

